[versions]
kotlin = "2.0.0"
agp = "8.3.0"
compose = "1.6.2"
composeCompiler = "1.5.11"
room = "2.6.1"
hilt = "2.51"
coroutines = "1.8.0"
retrofit = "2.10.0"
okhttp = "4.12.0"
coil = "2.6.0"
work = "2.9.0"
mpandroidchart = "3.1.0"
vico = "2.0.0"
palette = "1.0.0"
securityCrypto = "1.1.0-alpha06"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.12.0" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.8.1" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
vico-core = { module = "com.patrykandpatrick.vico:core", version.ref = "vico" }
palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "palette" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }

[bundles]
compose = ["compose-ui", "compose-material", "compose-ui-tooling", "compose-activity"]
room = ["room-runtime", "room-ktx"]
hilt = ["hilt-android"]
network = ["retrofit", "retrofit-converter-moshi", "okhttp-logging"]
